# Generated by Django 3.2.13 on 2022-09-01 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('duration', models.IntegerField(default=13)),
            ],
        ),
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2022, 9, 1, 13, 43, 25, 125560)),
        ),
    ]
