# Generated by Django 3.2.13 on 2022-09-01 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20220901_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 1, 14, 42, 17, 43502)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2022, 9, 1, 14, 42, 17, 43502)),
        ),
    ]
