# Generated by Django 3.2.13 on 2022-09-05 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20220901_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 6, 0, 37, 50, 55495)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2022, 9, 6, 0, 37, 50, 54498)),
        ),
    ]
